version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    groups:
      base-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
