[changelog]
header = """
# Changelog

"""
body = """
{% if version %}\
## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## Unreleased
{% endif %}\
### Changes

{% for commit in commits | filter(attribute="merge_commit", value=true) %}\
- {% if commit.remote.pr_labels is containing("dependencies") %}chore(deps): {% endif %}{{ commit.remote.pr_title | trim }} (#{{ commit.remote.pr_number }})
{% endfor %}\
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^chore\\(release\\)", skip = true },
  { message = "^no changelog$", skip = true },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^chore", group = "Chores" },
  { message = "^docs", group = "Documentation" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^test", group = "Tests" },
  { message = "^ci", group = "CI" },
  { message = "^Bump", group = "Dependencies" },
  { message = ".*", group = "Other" },
]
filter_commits = false
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+(?:-rc[0-9]+)?$"
sort_commits = "oldest"
